### ISSUE TITLE
Interface-specific DNS not set if not overriding local nameserver

### ISSUE THREAD

**Issue by handsomexdd1024** [juanfont/headscale#1547]
## Bug description

When connecting to headscale server, I configured `dns_config.override_local_dns` to false, and observed that `systemd-resolved`'s interface-specific for `tailscale0` is not set to 100.100.100.100. In general, I tested several configurations, and the results are here:
![image](https://github.com/juanfont/headscale/assets/36498278/aae2dcb1-be40-4dde-addf-fcbe3140603a)
I expect that 100.100.100.100 be set as interface-specific nameserver even when override_local_dns is not enabled, otherwise FQDNs internal to my tailnet (hostname.username.base_domain) will not be resolved by 100.100.100.100, and thus is not giving back correct responses.
Everything else works as expected.

## Environment

- OS: 
  - Headscale host: Debian 12.1 with `linux-6.1.0`
  - Tailscale client: Arch Linux Rolling with `linux-6.5.3`
- Headscale version: 0.22.3
- Tailscale version: 1.48.2

~~I'll post logs later~~

`resolvectl status tailscale0` outputs when connected to headscale:
```text
Link 8 (tailscale0)
    Current Scopes: none
         Protocols: -DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
        DNS Domain: my.tailnet.domain ~0.e.1.a.c.5.1.1.a.7.d.f.ip6.arpa (and etc)
```
when connected to tailscale official server:
```text
Link 8 (tailscale0)
    Current Scopes: DNS
         Protocols: -DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 100.100.100.100
       DNS Servers: 100.100.100.100
        DNS Domain: my.tailnet.domain ~0.e.1.a.c.5.1.1.a.7.d.f.ip6.arpa (and etc)
```

## To Reproduce

- Turn off `override_local_dns`
- Connect to headscale with **--accept-dns=true**
- Run `resolvectl status tailscale0` on the client to check results

**Comment by hrtkpf** [comment]
I can confirm this issue.

Related: https://github.com/juanfont/headscale/issues/660#issuecomment-1712839303, #905

**Comment by handsomexdd1024** [comment]
@9Ninety Brilliant solution! Thank you so much.

**Comment by hrtkpf** [comment]
I think this is still relevant.

**Comment by almereyda** [comment]
I'm not able to reproduce this on Ubuntu 23.10 (systemd 253) with latest Headscale 0.23.0-alpha5 and Tailscale 1.60.1 and `override_local_dns: false` and [`--accept-dns` enabled](https://github.com/tailscale/tailscale/pull/593#issuecomment-663191423).

```sh
$ tailscale debug prefs | jq '.CorpDNS'
true
```

<details><summary>`resolvectl status tailscale0`</summary>
<p>

```
Link 4 (tailscale0)
    Current Scopes: DNS
         Protocols: -DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 100.100.100.100
       DNS Servers: 100.100.100.100
        DNS Domain: current-user.example.internal ~0.e.1.a.c.5.1.1.a.7.d.f.ip6.arpa
                    ~100.100.in-addr.arpa ~101.100.in-addr.arpa
                    ~102.100.in-addr.arpa ~103.100.in-addr.arpa
                    ~104.100.in-addr.arpa ~105.100.in-addr.arpa
                    ~106.100.in-addr.arpa ~107.100.in-addr.arpa
                    ~108.100.in-addr.arpa ~109.100.in-addr.arpa
                    ~110.100.in-addr.arpa ~111.100.in-addr.arpa
                    ~112.100.in-addr.arpa ~113.100.in-addr.arpa
                    ~114.100.in-addr.arpa ~115.100.in-addr.arpa
                    ~116.100.in-addr.arpa ~117.100.in-addr.arpa
                    ~118.100.in-addr.arpa ~119.100.in-addr.arpa
                    ~120.100.in-addr.arpa ~121.100.in-addr.arpa
                    ~122.100.in-addr.arpa ~123.100.in-addr.arpa
                    ~124.100.in-addr.arpa ~125.100.in-addr.arpa
                    ~126.100.in-addr.arpa ~127.100.in-addr.arpa
                    ~64.100.in-addr.arpa ~65.100.in-addr.arpa
                    ~66.100.in-addr.arpa ~67.100.in-addr.arpa
                    ~68.100.in-addr.arpa ~69.100.in-addr.arpa
                    ~70.100.in-addr.arpa ~71.100.in-addr.arpa
                    ~72.100.in-addr.arpa ~73.100.in-addr.arpa
                    ~74.100.in-addr.arpa ~75.100.in-addr.arpa
                    ~76.100.in-addr.arpa ~77.100.in-addr.arpa
                    ~78.100.in-addr.arpa ~79.100.in-addr.arpa
                    ~80.100.in-addr.arpa ~81.100.in-addr.arpa
                    ~82.100.in-addr.arpa ~83.100.in-addr.arpa
                    ~84.100.in-addr.arpa ~85.100.in-addr.arpa
                    ~86.100.in-addr.arpa ~87.100.in-addr.arpa
                    ~88.100.in-addr.arpa ~89.100.in-addr.arpa
                    ~90.100.in-addr.arpa ~91.100.in-addr.arpa
                    ~92.100.in-addr.arpa ~93.100.in-addr.arpa
                    ~94.100.in-addr.arpa ~95.100.in-addr.arpa
                    ~96.100.in-addr.arpa ~97.100.in-addr.arpa
                    ~98.100.in-addr.arpa ~99.100.in-addr.arpa ~other-user.example.internal
                    ~data.example.internal ~third_user.example.internal ~road.example.internal
```

</p>
</details> 

Is this maybe an upstream condition, eventually related to distribution-specific packaging/configuration?

**Comment by mimnix** [comment]
Same issue here with the following setup:

    Headscale host: docker image `headscale/headscale:0.23.0-alpha8`
    Tailscale client: v1.64.0 on Arch Linux Rolling with `linux-6.8.5`

**Comment by handsomexdd1024** [comment]
Recent tests showed that this bug has been fixed somehow, so I'm closing this issue.

**Comment by Matic-M** [comment]
This issue has not been resolved

**Comment by mastier** [comment]
Still failed on me on some older system like ubuntu jammy and tailscale 1.88.4 or debian

the problem dissaperared when I upgraded to the newest tailscale client 1.90.
https://pkgs.tailscale.com/stable/#ubuntu-jammy

For me the problem it was overriding the default resolved stub also
not it works correctly

**Comment by Creepios** [comment]
I guess its not solved, happening for me on windows. Android just works fine but in windows, i have to set these dns server manually
