### ISSUE TITLE
Machine waiting for OIDC auth is spamming the server with requests

### ISSUE THREAD

**Issue by iSchluff** [juanfont/headscale#603]
**Bug description**
After tailscale up the machine is spamming the control server with http-requests waiting for the user to complete the oidc auth.
This is causing considerable load on the server, with a constant 80 requests/s in one instance.
![image](https://user-images.githubusercontent.com/1429641/171422471-17adde25-0b0c-4b66-9d4f-b67290ddac04.png)

The logs look like follows
```
[GIN] 2022/06/01 - 13:53:22 | 200 |    1.479334ms | xx.xx.141.118 | POST     "/machine/67aa1e887ece306e52c5f8b27663042a3cd4421d0ef3d94d9a74f1e09761c92c"
[GIN] 2022/06/01 - 13:53:22 | 200 |    1.899759ms | xx.xx.141.118 | POST     "/machine/67aa1e887ece306e52c5f8b27663042a3cd4421d0ef3d94d9a74f1e09761c92c"
[GIN] 2022/06/01 - 13:53:22 | 200 |    1.678392ms | xx.xx.141.118 | POST     "/machine/67aa1e887ece306e52c5f8b27663042a3cd4421d0ef3d94d9a74f1e09761c92c"
[GIN] 2022/06/01 - 13:53:22 | 200 |    1.717471ms | xx.xx.141.118 | POST     "/machine/67aa1e887ece306e52c5f8b27663042a3cd4421d0ef3d94d9a74f1e09761c92c"
[GIN] 2022/06/01 - 13:53:22 | 200 |    1.594622ms | xx.xx.141.118 | POST     "/machine/67aa1e887ece306e52c5f8b27663042a3cd4421d0ef3d94d9a74f1e09761c92c"
[GIN] 2022/06/01 - 13:53:22 | 200 |    1.819499ms | xx.xx.141.118 | POST     "/machine/67aa1e887ece306e52c5f8b27663042a3cd4421d0ef3d94d9a74f1e09761c92c"
[GIN] 2022/06/01 - 13:53:22 | 200 |    1.620602ms | xx.xx.141.118 | POST     "/machine/67aa1e887ece306e52c5f8b27663042a3cd4421d0ef3d94d9a74f1e09761c92c"
[GIN] 2022/06/01 - 13:53:22 | 200 |    1.890737ms | xx.xx.141.118 | POST     "/machine/67aa1e887ece306e52c5f8b27663042a3cd4421d0ef3d94d9a74f1e09761c92c"
[GIN] 2022/06/01 - 13:53:22 | 200 |    1.807969ms | xx.xx.141.118 | POST     "/machine/67aa1e887ece306e52c5f8b27663042a3cd4421d0ef3d94d9a74f1e09761c92c"
```

I assume the official tailscale control server just holds the connection open in that case instead of closing with code 200? Maybe headscale should do something similar?

From https://github.com/tailscale/tailscale/blob/6f700925cef22d8b2a100840c8d9eb084dadfece/control/controlclient/direct.go#L265-L271 I gather that headscale would need to implement long-poll for the login url aswell.

**To Reproduce**
Run tailscale up --login-server=https://....

**Details**
- Headscale commit be25bbce92fb1be3c233ad286971bd738923c352
- Tailscale 1.22.2
- OS: Linux
- Kernel: 5.15.19

**Comment by juanfont** [comment]
This is closely related to #706, and (very partially) addressed in #725.

Will remain open for the time being, because indeed we need to implement long polling.

**Comment by juanfont** [comment]
@iSchluff in 0.16.1 we have implemented a workaround to help on this. Can you give it a try?

**Comment by iSchluff** [comment]
> @iSchluff in 0.16.1 we have implemented a workaround to help on this. Can you give it a try?

unfortunately I still see the same behavior with 0.16.3
![Screenshot 2022-08-18 at 18-17-48 Headscale - Grafana](https://user-images.githubusercontent.com/1429641/185444755-c04afc67-5dec-4dc8-82be-9ab2f5013677.png)

```
$ nomad alloc exec -i -t -task headscale 459f7965-ab8b-7713-4b74-cde04ce541da /bin/headscale version
v0.16.3
```

**Comment by kradalby** [comment]
Not sure if anything has happened in 0.17, can you try that?

**Comment by kradalby** [comment]
This seems resolved, also might be part of #727
